### ISSUE TITLE
STINGER ingest rate slows dramatically during inserts

### ISSUE THREAD

**Issue by tgoodyear** [stingergraph/stinger#170]
Possibly related to #131 , after ~30M edges the ingest rate drops below 10k/s on `dev` branch for graphs which contain high-degree vertices. Example edgelist available upon request.

**Comment by ehein6** [comment]
High-degree vertices take longer to update due to the choice of data structure, but this slowdown is aggravated by the static work partitioning in the edge ingest for loop. A dynamic schedule with a large chunksize seems to help, see #198.

**Comment by tgoodyear** [comment]
I think this can be closed thanks to @ehein6's #208 PR
