### ISSUE TITLE
How to get the outdegree of a vertex?

### ISSUE THREAD

**Issue by rohitvarkey** [stingergraph/stinger#200]
Hi,

I wanted to find the outdegree of a vertex in a `stinger` graph. Looking through the examples, I see that `stinger_outdegree` is used. But it seems to be deprecated and not to be used as it shows up in the `stinger_deprecated.h` file. The [new function](https://github.com/stingergraph/stinger/blob/24f533b0c21adcc24946a715afe3de42c41c0abb/lib/stinger_core/inc/stinger_deprecated.h#L33) provided there is `stinger_outdegree_get`. The [definition](https://github.com/stingergraph/stinger/blob/24f533b0c21adcc24946a715afe3de42c41c0abb/lib/stinger_core/src/stinger.c#L71-L74) of `stinger_outdegree_get` is commented out.

Is there any other way I can obtain the outdegree of a vertex?

Thanks,
Rohit

**Comment by davidediger** [comment]
`stinger_outdegree_get(S, v)` is the proper function.  The first parameter, S, is the pointer to the graph data structure.  The second parameter, v, is the logical vertex ID.

**Comment by rohitvarkey** [comment]
Ah. I see its defined in the header file itself. Sorry for the noise.

**Comment by rohitvarkey** [comment]
I was trying to access `stinger_outdegree_get` using a call to the `libstinger_core` library when it said the symbol could not be found. I tried a `nm -m libstinger_core` and saw that `stinger_outdegree_get` was a non-external symbol.  

```shell
$ nm -m libstinger_core.dylib | grep stinger_outdegree_get
0000000000002a70 (__TEXT,__text) non-external _stinger_outdegree_get
```

Is the [definition](https://github.com/stingergraph/stinger/blob/dev/lib/stinger_core/inc/stinger.h#L186-L189) of `stinger_outdegree_get` as a `static inline` function the reason for it being a non-external symbol? 

Is there any other function that would let me get the outdegree using the shared library?

**Comment by ehein6** [comment]
You're right, looks like the definition was changed to inline a while back  in https://github.com/stingergraph/stinger/commit/dcddcdae323dee9ac062363cb8061731e5067d1d and no one has tried to use it externally since then. 

I added an extern defintion for you, check out https://github.com/ehein6/stinger/tree/stinger-outdegree-get-extern and let me know if that fixes the problem.

**Comment by rohitvarkey** [comment]
@ehein6 Thanks! But it didn't work. I've made a PR - #203 with a fix that worked for me.
