### ISSUE TITLE
Getting the results out of stinger

### ISSUE THREAD

**Issue by jayavanth** [stingergraph/stinger#236]
I'm running stinger like in the readme:
`env STINGER_MAX_MEMSIZE=1G ./bin/stinger_server`
`./bin/stinger_json_rpc_server`
`./bin/stinger_pagerank`
`./bin/stinger_rmat_edge_generator -n 100000 -x 10000`

How do I get the pagerank out of it? I used the `-k` option mentioned here https://github.com/stingergraph/stinger/issues/74, but I don't know how to interpret the .rslt file.

**Comment by ehein6** [comment]
Here's the code that writes the .rslt file: https://github.com/stingergraph/stinger/blob/63bcd5d4a95ffae6cef3d4d32706f69fbeb28c2e/lib/stinger_net/src/stinger_server_state.cpp#L560

It's essentially a few headers then a binary dump of the pagerank value for each vertex.

**Comment by jayavanth** [comment]
Is there an easier way other than dumping the .rslt to get top k pageranks?

**Comment by ehein6** [comment]
Depends on what you're trying to do.

If you're just wanting to run pagerank once on a static graph, then the client/server architecture is probably overkill. Just write your own standalone program and link against `stinger_core` and `stinger_alg`. Creates the graph with `stinger_new_full()`, insert your edges with `stinger_insert_edge`, call `pagerank()`, and print the results however you like.

If you still want to use the server approach, you can use `curl` to make requests to the JSON RPC server and get the results that way. I've not used it personally, but there's also a tool in `util/management` that will let you talk to the server while it's running.

**Comment by jayavanth** [comment]
Thanks for the suggestion. I'm thinking of getting it from here: https://github.com/stingergraph/stinger/blob/63bcd5d4a95ffae6cef3d4d32706f69fbeb28c2e/src/clients/algorithms/pagerank/src/pagerank.c#L135
However, the only problem is that I'm only able to the vertex ID and not the actual name of the vertex. I'm guessing this `stinger_mapping_nv(alg->stinger)` maps from vertices to vertex IDs. Is there a way to get the vertex name?

**Comment by ehein6** [comment]
Actually `stinger_mapping_nv()` returns the number of vertices in the mapping.  
To convert from vertex name to ID, use `stinger_mapping_lookup()`
To convert from vertex ID to name, use `stinger_mapping_physid_get()` (which makes a copy of the string) or `stinger_mapping_physid_direct()` (which gives you a pointer to the existing string).
You will also need to call `stinger_mapping_create()` to map names to physical vertex ID's as you insert edges.

I'm happy to keep answering your questions, but we've drifted from the original issue topic. Please contact me via the email on my profile page.

**Comment by jayavanth** [comment]
Thanks @ehein6, I was able to get the vertex name. I'll contact you by mail if I have any non-bug Stinger questions.

**Comment by jpfairbanks** [comment]
@jayavanth were you able to get what you need? Can we close this issue?

**Comment by jayavanth** [comment]
Yes, I'll close it. Thanks!
