### ISSUE TITLE
How can I run stinger without a network?

### ISSUE THREAD

**Issue by gzgywh** [stingergraph/stinger#239]
Our laboratory can't connect network for safety.So I wonder whether stinger can import data and run without network?And how can I modify the source code?Thank you very much

**Comment by jpfairbanks** [comment]
Yes that will work as long as you have a way to get the data into your environment. You can run all stinger components on one machine and read the data from disk.

**Comment by gzgywh** [comment]
That means I don't need modify the source code?The problem is when I have network,I can import the csv data and json data and run,but when the network is disconnected the data import may be failed.

**Comment by jpfairbanks** [comment]
I'm not sure what "data import may be failed" means. You can provide data from a file to the CSV or JSON ingest programs. 

If that isn't working, please include the exact commands that you are running and error messages that you are receiving.

**Comment by gzgywh** [comment]
That means if I have network,I can import data to stinger and run success, but  if I didn't have network,I can't import the data to stinger,and when I run the algorithm like pagerank,I can't see any picture in html file,so I wonder if this  problem can be solved?

**Comment by gzgywh** [comment]
Sorry,we can import the data success ,but  we can't see anything in html file when we run an algorithm like pagerank and k-core and so on .So we want to know how can we do to make Stinger show the Visualization to us if our network is disconnected?

**Comment by jpfairbanks** [comment]
The JavaScript libraries for the website are loaded at runtime. You would need to download them and patch the paths in the HTML. Here is a file that shows dependencies on bootstrap and underscore.js for example. https://github.com/stingergraph/stinger/blob/master/util/graph_explorer/page_rank_top.html

**Comment by jpfairbanks** [comment]
You could also import them and serve them up yourself using a webserver and manipulation of /etc/hosts

**Comment by gzgywh** [comment]
I will try, thank you very much!

**Comment by gzgywh** [comment]
We run stinger success and can visit the html without network, thank you very much!
