### ISSUE TITLE
How can stinger link to kafka?

### ISSUE THREAD

**Issue by chtt66** [stingergraph/stinger#241]
I am sorry to disturb you, someone asked me to cache the data for graph analysis in kafka, stinger  extracts and analyzes the data directly from kafka, I would like to know how stinger and kafka for data communication? This problem makes me very annoying, looking forward to your response.

**Comment by zlksilence** [comment]
what is kafka?

**Comment by tgoodyear** [comment]
Hello, STINGER has no built-in support for Apache Kafka. You can build an application that interfaces with Kafka and STINGER through the STINGER [Flask API](https://github.com/stingergraph/stinger/tree/master/util) [(code)](https://github.com/stingergraph/stinger/blob/master/util/flask/stinger_flask.py), the [Python bindings](https://github.com/stingergraph/stinger/blob/master/src/py/stinger/stinger_core.py), by writing a [stream client](https://github.com/stingergraph/stinger/tree/master/src/clients/streams) or likely some combination of all three.
