### ISSUE TITLE
Connected Components Standalone is not working for me.

### ISSUE THREAD

**Issue by EliosSs** [stingergraph/stinger#246]
Hey, Good Morning. I'm trying to run the Connected Components as standalone program. I'm using a graph file and an action file generated with the rmat_graph_generator.

Im executing the connected components stand alone like this:
(since build directory)
./lib/stinger_connected_components g.20.8.bin a.20.8.100000.bin
The CC program runs and creates the STINGER graph successfully, but when it calls the routine "connected_components_stinger" i get a segmentation fault error. Is this correct? am i doing anything wrong? it is the correct way to execute the program? with those parameters i mean? or i need no specify the number of batches and the batches?

If someone could help me i will be grateful. Thanks in advance.

Regards.

**Comment by ehein6** [comment]
You seem to be using an old version of stinger. The standalone version of `stinger_connected_components` was removed a while ago. 

If you're looking to execute algorithms from stinger in a standalone environment, try https://github.com/DynoGraph/stinger-dynograph .
