### ISSUE TITLE
template.csv for streaming in edges from a csv file

### ISSUE THREAD

**Issue by abasak24** [stingergraph/stinger#248]
Hello,
I am trying to use the server-client mode and trying to stream in edges from a csv file. My .csv file contains integers in the form of SOURCE_ID, DESTINATION_ID, TIMESTAMP, WEIGHT. However, I think to run the ./bin/stinger_csv_stream, there needs to be a template.csv file. My template file is not working. What should a template file look like for the csv? 

Thanks!

**Comment by davidediger** [comment]
Your template.csv should probably contain a single line like
`$source_str1,$destination_str1,$time1,$weight1`

**Comment by abasak24** [comment]
Thanks!
