### ISSUE TITLE
Are updates thread-safe?

### ISSUE THREAD

**Issue by whatsthecraic** [stingergraph/stinger#255]
Hi there,
can, for instance invocations of stinger_insert_edge or stinger_remove_edge_pair, invoked concurrently by multiple threads? In other words, is the interface for edge updates thread-safe?

**Comment by ehein6** [comment]
Yes. 

See also the batch update functions added in https://github.com/stingergraph/stinger/pull/208, which are more efficient than calling `stinger_insert_edge` in parallel if you have many updates to do at once.

**Comment by whatsthecraic** [comment]
Have deletions been implemented  in this batch mode?

From the associated ticket, it states:
`
I've decided to omit concurrent deletion tests for now. OpenMP won't let me call stinger_batch_incr_edges in parallel with stinger_remove_edge, because this would result in a omp parallel for nested inside an omp section. To fix this, stinger_batch functions should handle insertions and deletions together. While this is conceptually possible, it would be quite a bit more work, which doesn't seem worthwhile because concurrent insertion/deletion isn't actually being used anywhere at the moment. Let's just get this merged in, and we can create an issue to integrate optimized batch deletion.
`

**Comment by whatsthecraic** [comment]
I don't get this part. The paper [1] states that both insertions and deletions are performed in batches. Is it possible to obtain the source code of the experiments in [1]?

[1] David Ediger et al, STINGER: High Performance Data Structure for Streaming Graphs, IEEE HPEC'12. http://www.stingergraph.com/papers/HPEC12_Ediger.pdf

**Comment by ehein6** [comment]
The `stinger_batch` functions I wrote are basically a re-implementation of the algorithm discussed in [1]. If you dig through the git history of this repo you can find the old code. I doubt it would be compatible with the existing code base, for one thing it did not handle creating in-edges. 

As far as I know it should still be safe to launch individual deletions in parallel with `stinger_batch` functions. I just didn't write a unit test for it.
