### ISSUE TITLE
Running Issue 

### ISSUE THREAD

**Issue by talnish** [stingergraph/stinger#256]
I am pretty new to this tool, and this is the first time I am trying to build it.
I cloned the repo and built it from both dev and master branches (it builds fine).
When I try to run it using the command provided in the README, I get stuck on the first command:

`env STINGER_MAX_MEMSIZE=1G ./bin/stinger_server`

It gets stuck at trying to acquire lock and never comes out of it:

`dequeue_batch 181: Attempt to acquire lock`

Am I missing something here?

**Comment by ehein6** [comment]
Are you running any clients to connect to the server? If not, then the server is working normally and just waiting for something to do. 

IIRC, that log statement is normal and not indicative of a deadlock.
